"""
Shared "Settings Calculator" helpers: turn equipment ratings into a
suggested starting point for relay settings, the same direction the
settings docs' own "Select taps" / "Setting Criteria" sections work in
(ratings -> CT-matching tap -> bias/minimum-operate/HOC), rather than the
rest of the app's normal direction (settings -> verdict on a given input).

Several different kinds of numbers come out of this:
  - CT-matching tap (T_E): a hard formula, T_E = relay rated current / relay
    current at rated load. Exact, and directly comparable to each settings
    doc's own worked example.
  - Bias / Minimum Operate / HOC: these are engineering judgment calls even
    in the source documents themselves (e.g. "the bias must be set higher
    than the maximum differential operating current generated by a maximum
    external fault" - Overall GSUT-GEN doc, Setting Criteria section). What's
    offered here is a rule-of-thumb starting point derived from the
    commissioning-time tap mismatch, NOT a substitute for a through-fault/
    inrush coordination study.
  - Generator differential (Pickup/Slope/Break) and motor overload/time-
    overcurrent settings: same spirit - reuse whatever "typical" value is
    already documented in this app's engine defaults or view-layer help
    text (rather than inventing new numbers), and where a genuine trip-time
    margin exists to solve for (Curve Multiplier, Time Dial), pick the
    smallest/most-sensitive candidate that still clears the motor's own
    starting profile without exceeding its safe-stall time - the same
    "most sensitive setting that still avoids a nuisance trip" principle
    each page's own Starting/Stall Margin Check already applies by hand.
"""

from engines.motor import MotorTimeOvercurrentRelay
from engines.motor_869 import Motor869Relay


def suggest_ct_matching_tap(i_rated_pri, ct_ratio, ct_secondary_rating, delta_factor=1.0, relay_rated_current=5.0):
    """T_E = I_N / I_relay - the ideal (unrounded) CT-matching tap for a
    winding at rated load, same formula as each settings doc's worked
    example (e.g. EXCT: T1_E = I_N / I_RH = 5 / 4.28 = 1.168)."""
    effective_ratio = ct_ratio / ct_secondary_rating if ct_secondary_rating > 0 else ct_ratio
    i_sec = i_rated_pri / effective_ratio if effective_ratio > 0 else 0.0
    i_relay = i_sec * delta_factor
    return relay_rated_current / i_relay if i_relay > 0 else None


def mismatch_ratio_pct(tap_currents):
    """Settings docs' own mismatch formula, generalized to N windings:
    (largest - smallest) / smallest tap-corrected current, as a percent.
    tap_currents: list of each winding's tap-corrected relay current (pu or A)."""
    valid = [v for v in tap_currents if v is not None and v > 0]
    if len(valid) < 2:
        return None
    smallest, largest = min(valid), max(valid)
    return ((largest - smallest) / smallest) * 100.0 if smallest > 0 else None


def suggest_bias_settings(mismatch_pct, num_windings=2):
    """
    Rule-of-thumb starting points - NOT a substitute for a coordination study:
      - Minimum Operate: floored at a manufacturer-typical 20%, and pushed
        higher than 2x the worst commissioning CT/tap mismatch so healthy
        through-load can never nuisance-trip from tap rounding alone.
      - Bias (slope): set at or above the Minimum Operate floor - a 3-winding
        relay is bumped up further since an extra winding's CT error can
        stack in the same direction on a through-fault.
      - HOC: manufacturer-typical unrestrained multiple for the relay family
        (5x tap current, 2-winding; 8x, 3-winding, per this app's own CAC1/
        CAC2 presets) - must clear max inrush/asymmetrical offset in the
        field, which this rule of thumb cannot see.
    """
    mismatch_pct = mismatch_pct if mismatch_pct is not None else 0.0
    suggested_min_operate = max(20.0, round(mismatch_pct * 2, 1))
    suggested_bias = max(suggested_min_operate, 20.0 if num_windings == 2 else 30.0)
    suggested_hoc = 5.0 if num_windings == 2 else 8.0
    return {
        "min_operate_pct": suggested_min_operate,
        "bias_pct": suggested_bias,
        "hoc_multiple": suggested_hoc,
        "basis": (
            f"Min Operate ≈ 2x the worst-case commissioning mismatch ({mismatch_pct:.2f}%), floored "
            f"at a manufacturer-typical 20% so tap rounding alone can't nuisance-trip a healthy load. "
            f"Bias set at or above that floor. HOC per this relay family's manufacturer-typical "
            f"unrestrained multiple ({'5x' if num_windings == 2 else '8x'} tap current). "
            f"Engineering review required — always confirm against a real through-fault/inrush "
            f"coordination study before applying."
        ),
    }


def suggest_generator_differential_settings(mismatch_pct):
    """
    Rule-of-thumb starting points for GE G60 differential settings (Pickup,
    Slope 1/2, Break 1/2) - NOT a substitute for a coordination study.

    Pickup and Slope 1 scale from the documented range's low end (5%, 15%)
    toward its high end (10%, 25% - "conventionally set low, 5-10% typical",
    per views/generator.py's own help text) as CT mismatch increases, same
    spirit as suggest_bias_settings' mismatch scaling: more margin is needed
    to avoid nuisance tripping as tap-rounding error between the Neutral and
    Terminal sides grows. Slope 2 / Break 1 / Break 2 use
    AdvancedDifferentialRelay's own manufacturer-typical constructor
    defaults (60%, 1.10pu, 6.00pu) - reused, not re-derived, since no
    mismatch-sensitivity applies to them the way it does to Pickup/Slope 1.
    """
    mismatch_pct = mismatch_pct if mismatch_pct is not None else 0.0
    pickup_pu = min(0.10, max(0.05, 0.05 + mismatch_pct * 0.005))
    slope_1_pct = min(25.0, max(15.0, 15.0 + mismatch_pct * 0.5))
    return {
        "i_pickup": round(pickup_pu, 3),
        "slope_1": round(slope_1_pct, 1),
        "slope_2": 60.0,
        "break_1": 1.10,
        "break_2": 6.00,
        "basis": (
            f"Pickup and Slope 1 scale up from the documented range's low end (5%, 15%) toward its high "
            f"end (10%, 25%) as CT mismatch increases ({mismatch_pct:.2f}% mismatch here) — more margin is "
            f"needed to avoid nuisance tripping as tap-rounding error grows. Slope 2/Break 1/Break 2 use "
            f"this relay's own manufacturer-typical defaults (60%, 1.10pu, 6.00pu). Engineering review "
            f"required — always confirm against a real through-fault/inrush coordination study."
        ),
    }


def suggest_motor_overload_settings(
    motor_fla, ct_ratio, ground_ct_ratio,
    locked_rotor_amps_100=None, locked_rotor_amps_80=None,
    accel_time_100=None, accel_time_80=None,
    safe_stall_100=None, safe_stall_80=None,
):
    """
    Rule-of-thumb starting points for a GE Multilin 469/869 (Motor869Relay)
    overload/instantaneous/ground-fault/unbalance settings sheet.

    Overload Pickup (115%), Instantaneous multiple (2.0x locked rotor),
    Ground Fault fraction (10% of ground CT), and Unbalance alarm/trip
    (15%/15%) are all reused directly from Motor869Relay's own documented
    constructor defaults - not re-derived, since those defaults already ARE
    this relay family's stated "typical" values (confirmed against this
    app's own Current Settings help text, which checks pickup against the
    same 110-115% band).

    Curve Multiplier is the one genuine solve: if a full starting profile is
    on record (locked rotor current, acceleration time, and safe stall time
    at both 100% and 80% voltage), tries CM candidates from 1.0 to 8.0 and
    returns the smallest one whose overload trip time clears BOTH
    acceleration times while staying under BOTH safe-stall times - the same
    "most sensitive setting that still avoids a nuisance trip" check each
    motor page's own Starting/Stall Margin Check already performs by hand.
    Falls back to the engine's own default (4.0) if that data isn't on
    record, flagged as unverified.
    """
    overload_pickup_pct = 115.0
    inst_pickup_amps = 2.0 * locked_rotor_amps_100 if locked_rotor_amps_100 else None
    gf_pickup_amps = 0.1 * ground_ct_ratio
    unbal_alarm_pct = 15.0
    unbal_trip_pct = 15.0

    have_starting_data = all(
        v is not None for v in
        (locked_rotor_amps_100, locked_rotor_amps_80, accel_time_100, accel_time_80, safe_stall_100, safe_stall_80)
    )
    curve_multiplier = 4.0
    cm_basis = (
        "No starting/safe-stall data on record for this motor — using this relay family's typical "
        "default (CM 4.0). Verify once starting data is available."
    )
    if have_starting_data:
        best = None
        cm = 1.0
        while cm <= 8.0:
            probe = Motor869Relay(
                ct_ratio=1.0, ct_secondary_rating=1.0, motor_fla=motor_fla, curve_multiplier=cm,
                inst_pickup_multiple_of_ct=1.0,
            )
            t100 = probe.calculate_overload_trip_time(locked_rotor_amps_100)
            t80 = probe.calculate_overload_trip_time(locked_rotor_amps_80)
            ok = (
                t100 is not None and accel_time_100 < t100 < safe_stall_100
                and t80 is not None and accel_time_80 < t80 < safe_stall_80
            )
            if ok:
                best = cm
                break
            cm = round(cm + 0.5, 1)
        if best is not None:
            curve_multiplier = best
            cm_basis = (
                f"Smallest Curve Multiplier (of 1.0–8.0) that still clears both starting profiles "
                f"(100%V and 80%V) while staying under both safe-stall times."
            )
        else:
            curve_multiplier = 8.0
            cm_basis = (
                "No Curve Multiplier from 1.0–8.0 clears both starting profiles at once with this "
                "motor's recorded data — real settings sometimes accept this trade-off too (check this "
                "motor's own Starting/Stall Margin Check to see which voltage is marginal). Showing the "
                "most conservative (largest) value tested as a starting point."
            )

    return {
        "overload_pickup_pct": overload_pickup_pct,
        "curve_multiplier": curve_multiplier,
        "inst_pickup_amps": inst_pickup_amps,
        "gf_pickup_amps": gf_pickup_amps,
        "unbal_alarm_pct": unbal_alarm_pct,
        "unbal_trip_pct": unbal_trip_pct,
        "basis_overload": "Manufacturer-typical pickup band is 110–115% FLA; 115% is this relay family's documented default.",
        "basis_cm": cm_basis,
        "basis_inst": "Set at ~200% of locked rotor current, this relay family's documented starting criterion." if inst_pickup_amps else "Needs Locked Rotor Current on record to suggest.",
        "basis_gf": "10% of the ground CT's primary rating, this relay family's documented default fraction.",
        "basis_unbal": "15% alarm / 15% trip, this relay family's documented defaults.",
    }


def suggest_time_overcurrent_settings(
    motor_fla, ct_ratio, ct_secondary_rating,
    locked_rotor_amps_100=None, locked_rotor_amps_80=None,
    accel_time_100=None, accel_time_80=None,
    safe_stall_100=None, safe_stall_80=None,
    tap_51_options=None,
):
    """
    Rule-of-thumb starting points for a GE IFC66KD2A-style 50/50/51
    time-overcurrent relay (MotorTimeOvercurrentRelay) - ID Fan's own
    primary relay.

    51 Tap reuses the exact "ideal tap ≈ FLA + 15%, snapped to the nearest
    available discrete tap" formula already computed inline in
    views/motor_idfan.py's own Current Settings caption - not re-derived,
    just exposed here too so the calculator and Current Settings agree.
    50A Pickup reuses this relay's own documented "~300% of locked rotor
    current" starting-inrush criterion (views/motor_idfan.py help text).
    50B Dropout is sized so its estimated pickup (dropout / 0.8, per
    GEK-49949) clears motor FLA by that same 15% margin as the 51 tap.

    Time Dial is solved the same way Curve Multiplier is for the 869: if a
    full starting profile is on record, tries candidates from 0.5 to 10.0
    at the suggested 51 tap and returns the smallest that clears both
    starting profiles while staying under both safe-stall times.
    """
    effective_ratio = ct_ratio / ct_secondary_rating if ct_secondary_rating > 0 else ct_ratio
    i_sec_at_fla = motor_fla / effective_ratio if effective_ratio > 0 else 0.0
    ideal_tap_51 = i_sec_at_fla * 1.15
    tap_51_options = tap_51_options or [2.5, 2.8, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.5]
    tap_51 = min(tap_51_options, key=lambda t: abs(t - ideal_tap_51))

    pickup_50a = round((3.0 * locked_rotor_amps_100) / effective_ratio, 1) if (locked_rotor_amps_100 and effective_ratio > 0) else None
    dropout_50b = round((1.15 * motor_fla / effective_ratio) * 0.8, 2) if effective_ratio > 0 else None

    have_starting_data = all(
        v is not None for v in
        (locked_rotor_amps_100, locked_rotor_amps_80, accel_time_100, accel_time_80, safe_stall_100, safe_stall_80)
    )
    time_dial = 4.5
    td_basis = (
        "No starting/safe-stall data on record for this motor — using a typical mid-range time dial "
        "(4.5). Verify once starting data is available."
    )
    if have_starting_data:
        best = None
        td = 0.5
        while td <= 10.0:
            probe = MotorTimeOvercurrentRelay(
                ct_ratio=ct_ratio, ct_secondary_rating=ct_secondary_rating,
                tap_51=tap_51, time_dial=td, pickup_50a=1e9, dropout_50b=1e9,
            )
            t100 = probe.calculate_51_trip_time(probe.relay_current(locked_rotor_amps_100))
            t80 = probe.calculate_51_trip_time(probe.relay_current(locked_rotor_amps_80))
            ok = (
                t100 is not None and accel_time_100 < t100 < safe_stall_100
                and t80 is not None and accel_time_80 < t80 < safe_stall_80
            )
            if ok:
                best = td
                break
            td = round(td + 0.5, 1)
        if best is not None:
            time_dial = best
            td_basis = (
                "Smallest Time Dial (of 0.5–10.0) that still clears both starting profiles while staying "
                "under both safe-stall times, at the suggested 51 tap."
            )
        else:
            time_dial = 10.0
            td_basis = (
                "No Time Dial from 0.5–10.0 clears both starting profiles at once at the suggested tap "
                "— real settings sometimes accept this trade-off too (check this motor's own Starting/"
                "Stall Margin Check to see which voltage is marginal). Showing the most conservative "
                "(largest) value tested as a starting point."
            )

    return {
        "tap_51": tap_51,
        "time_dial": time_dial,
        "pickup_50a": pickup_50a,
        "dropout_50b": dropout_50b,
        "basis_tap_51": f"Ideal tap ≈ FLA + 15% = {ideal_tap_51:.2f} A sec., snapped to the nearest available discrete tap.",
        "basis_time_dial": td_basis,
        "basis_pickup_50a": "Set at ~300% of locked rotor current, this relay's documented starting-inrush criterion." if pickup_50a else "Needs Locked Rotor Current on record to suggest.",
        "basis_dropout_50b": "Sized so its estimated pickup (dropout / 0.8) clears motor FLA by the same 15% margin as the 51 tap.",
    }
