"""
Shared "Settings Calculator" helpers: turn equipment ratings into a
suggested starting point for relay settings, the same direction the
settings docs' own "Select taps" / "Setting Criteria" sections work in
(ratings -> CT-matching tap -> bias/minimum-operate/HOC), rather than the
rest of the app's normal direction (settings -> verdict on a given input).

Two different kinds of numbers come out of this:
  - CT-matching tap (T_E): a hard formula, T_E = relay rated current / relay
    current at rated load. Exact, and directly comparable to each settings
    doc's own worked example.
  - Bias / Minimum Operate / HOC: these are engineering judgment calls even
    in the source documents themselves (e.g. "the bias must be set higher
    than the maximum differential operating current generated by a maximum
    external fault" - Overall GSUT-GEN doc, Setting Criteria section). What's
    offered here is a rule-of-thumb starting point derived from the
    commissioning-time tap mismatch, NOT a substitute for a through-fault/
    inrush coordination study.
"""


def suggest_ct_matching_tap(i_rated_pri, ct_ratio, ct_secondary_rating, delta_factor=1.0, relay_rated_current=5.0):
    """T_E = I_N / I_relay - the ideal (unrounded) CT-matching tap for a
    winding at rated load, same formula as each settings doc's worked
    example (e.g. EXCT: T1_E = I_N / I_RH = 5 / 4.28 = 1.168)."""
    effective_ratio = ct_ratio / ct_secondary_rating if ct_secondary_rating > 0 else ct_ratio
    i_sec = i_rated_pri / effective_ratio if effective_ratio > 0 else 0.0
    i_relay = i_sec * delta_factor
    return relay_rated_current / i_relay if i_relay > 0 else None


def mismatch_ratio_pct(tap_currents):
    """Settings docs' own mismatch formula, generalized to N windings:
    (largest - smallest) / smallest tap-corrected current, as a percent.
    tap_currents: list of each winding's tap-corrected relay current (pu or A)."""
    valid = [v for v in tap_currents if v is not None and v > 0]
    if len(valid) < 2:
        return None
    smallest, largest = min(valid), max(valid)
    return ((largest - smallest) / smallest) * 100.0 if smallest > 0 else None


def suggest_bias_settings(mismatch_pct, num_windings=2):
    """
    Rule-of-thumb starting points - NOT a substitute for a coordination study:
      - Minimum Operate: floored at a manufacturer-typical 20%, and pushed
        higher than 2x the worst commissioning CT/tap mismatch so healthy
        through-load can never nuisance-trip from tap rounding alone.
      - Bias (slope): set at or above the Minimum Operate floor - a 3-winding
        relay is bumped up further since an extra winding's CT error can
        stack in the same direction on a through-fault.
      - HOC: manufacturer-typical unrestrained multiple for the relay family
        (5x tap current, 2-winding; 8x, 3-winding, per this app's own CAC1/
        CAC2 presets) - must clear max inrush/asymmetrical offset in the
        field, which this rule of thumb cannot see.
    """
    mismatch_pct = mismatch_pct if mismatch_pct is not None else 0.0
    suggested_min_operate = max(20.0, round(mismatch_pct * 2, 1))
    suggested_bias = max(suggested_min_operate, 20.0 if num_windings == 2 else 30.0)
    suggested_hoc = 5.0 if num_windings == 2 else 8.0
    return {
        "min_operate_pct": suggested_min_operate,
        "bias_pct": suggested_bias,
        "hoc_multiple": suggested_hoc,
        "basis": (
            f"Min Operate ≈ 2x the worst-case commissioning mismatch ({mismatch_pct:.2f}%), floored "
            f"at a manufacturer-typical 20% so tap rounding alone can't nuisance-trip a healthy load. "
            f"Bias set at or above that floor. HOC per this relay family's manufacturer-typical "
            f"unrestrained multiple ({'5x' if num_windings == 2 else '8x'} tap current). "
            f"Engineering review required — always confirm against a real through-fault/inrush "
            f"coordination study before applying."
        ),
    }
